# Generated by Django 4.2.4 on 2023-09-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="end_date",
            field=models.DateField(blank=True, null="True"),
            preserve_default="True",
        ),
    ]
